allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  inferno: true
minimumReleaseAgeExclude:
  - devextreme-cli
overrides:
  nanoid@<3.3.17: ^3.3.17
  react-router@>=7.12.0 <8.3.0: ^8.3.0
