name: Deploy

on:
  workflow_dispatch:
    inputs:
      base_path:
        description: 'Custom base path (e.g. /my-repo/). Leave blank to auto-detect.'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      BASE_PATH: ${{ github.event.inputs.base_path != '' && github.event.inputs.base_path || format('/{0}/', github.event.repository.name) }}

    steps:
    - name: Get sources
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.0'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules

    - name: Install dependencies (npm ci)
      run: npm ci --no-audit --no-fund

    - name: Install Internal Package
      uses: DevExpress/github-actions/install-internal-package@main

    - name: Build
      run: |
        echo "Using BASE_PATH=$BASE_PATH"
        rm -rf dist
        npx vite build --base "$BASE_PATH"

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
      with:
        branch: gh-pages
        folder: dist
        clean: true
        target-folder: .

